---
name: On-demand ğŸ§‘â€ğŸ”¬

on:
  schedule:
    - cron: '45 3 * * 0'
  workflow_dispatch:

jobs:
  branch-cleanup:
    name: Branch Cleanup ğŸ§¹
    uses: insightsengineering/r.pkg.template/.github/workflows/branch-cleanup.yaml@main
    secrets:
      REPO_GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
  revdepcheck:
    name: revdepcheck â†©ï¸
    uses: insightsengineering/r.pkg.template/.github/workflows/revdepcheck.yaml@main
  rhub:
    name: R-hub ğŸŒ
    uses: insightsengineering/r.pkg.template/.github/workflows/rhub.yaml@main
